/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BpfPreview {
        /**
          * 标题
         */
        "zcTitle": string;
    }
    interface BpfUpload {
        /**
          * 可选的文件类型
         */
        "accept"?: string;
        /**
          * 应用编码
         */
        "appCode": string;
        /**
          * 业务模块编码（英文字母）
         */
        "bizModule": string;
        /**
          * 是否允许拖拽
         */
        "drag": Boolean;
        /**
          * 上传时的附加请求头
         */
        "headers"?: string;
        /**
          * 是否多文件上传
         */
        "multiple": Boolean;
        /**
          * 删除文件时，是否可同步删除OSS服务器上的文件：0-否，1-是
         */
        "ossDelete": string;
        /**
          * 终端来源：1-PC，2-APP
         */
        "source": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBpfPreviewElement extends Components.BpfPreview, HTMLStencilElement {
    }
    var HTMLBpfPreviewElement: {
        prototype: HTMLBpfPreviewElement;
        new (): HTMLBpfPreviewElement;
    };
    interface HTMLBpfUploadElement extends Components.BpfUpload, HTMLStencilElement {
    }
    var HTMLBpfUploadElement: {
        prototype: HTMLBpfUploadElement;
        new (): HTMLBpfUploadElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "bpf-preview": HTMLBpfPreviewElement;
        "bpf-upload": HTMLBpfUploadElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BpfPreview {
        /**
          * 标题
         */
        "zcTitle"?: string;
    }
    interface BpfUpload {
        /**
          * 可选的文件类型
         */
        "accept"?: string;
        /**
          * 应用编码
         */
        "appCode"?: string;
        /**
          * 业务模块编码（英文字母）
         */
        "bizModule"?: string;
        /**
          * 是否允许拖拽
         */
        "drag"?: Boolean;
        /**
          * 上传时的附加请求头
         */
        "headers"?: string;
        /**
          * 是否多文件上传
         */
        "multiple"?: Boolean;
        /**
          * 删除文件时，是否可同步删除OSS服务器上的文件：0-否，1-是
         */
        "ossDelete"?: string;
        /**
          * 终端来源：1-PC，2-APP
         */
        "source"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "bpf-preview": BpfPreview;
        "bpf-upload": BpfUpload;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bpf-preview": LocalJSX.BpfPreview & JSXBase.HTMLAttributes<HTMLBpfPreviewElement>;
            "bpf-upload": LocalJSX.BpfUpload & JSXBase.HTMLAttributes<HTMLBpfUploadElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
